name: Countries deploy
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run:
          echo "Hola Uriel"
      - name: Tell me the date
        run: date
      - run: ls -l



